import { randomUUID } from 'node:crypto';
import { env, finishJob, handleApiError, logError, readJson, requireUser, reserveJob, send, uploadAsset } from '../_lib.js';
import { moderate } from '../_moderation.js';

const sizes={square:'1024x1024',post:'1024x1536',story:'1024x1536',landscape:'1536x1024'};
function dataImage(v){const m=String(v||'').match(/^data:(image\/(?:png|jpeg|webp));base64,(.+)$/);return m?{type:m[1],buffer:Buffer.from(m[2],'base64')}:null}
function ext(type){return type==='image/png'?'png':type==='image/webp'?'webp':'jpg'}
function estimate(model,quality,size){const configured=Number(env(`OPENAI_IMAGE_COST_${String(quality).toUpperCase()}`));if(Number.isFinite(configured)&&configured>=0)return configured;const portrait=size!=='1024x1024';const base={low:portrait?.02:.015,medium:portrait?.07:.05,high:portrait?.24:.18,auto:portrait?.07:.05};return base[quality]??base.medium}
function err(status,d){const raw=d?.error?.message||d?.message||'';if(status===401)return'Der OpenAI API-Key ist ungültig.';if(status===403)return'OpenAI hat diese Bildfunktion nicht freigegeben.';if(status===429)return'OpenAI-Guthaben oder Limit erreicht.';return raw||`OpenAI-Bildfehler (${status}).`}
async function generate({key,model,prompt,size,quality,background,reference,mask,format}){let response;if(reference){const image=dataImage(reference);if(!image)throw Object.assign(new Error('Referenzbild ist ungültig.'),{status:400});const form=new FormData();for(const [k,v] of Object.entries({model,prompt,size,quality,background,output_format:format,n:'1'}))form.append(k,v);if(format!=='png')form.append('output_compression','88');form.append('image',new Blob([image.buffer],{type:image.type}),`image.${ext(image.type)}`);if(mask){const mi=dataImage(mask);if(!mi||mi.type!=='image/png')throw Object.assign(new Error('Maske muss eine PNG-Datei mit Transparenz sein.'),{status:400});form.append('mask',new Blob([mi.buffer],{type:'image/png'}),'mask.png')}response=await fetch('https://api.openai.com/v1/images/edits',{method:'POST',headers:{Authorization:`Bearer ${key}`},body:form})}else{response=await fetch('https://api.openai.com/v1/images/generations',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,prompt,size,quality,background,output_format:format,output_compression:format==='png'?undefined:88,n:1})})}const data=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(err(response.status,data)),{status:response.status,technical:data?.error?.message});const item=data?.data?.[0]||{};if(item.b64_json)return{buffer:Buffer.from(item.b64_json,'base64'),revisedPrompt:item.revised_prompt||'',usage:data.usage||item.usage||null};if(item.url){const r=await fetch(item.url);if(!r.ok)throw new Error('OpenAI-Bild konnte nicht geladen werden.');return{buffer:Buffer.from(await r.arrayBuffer()),revisedPrompt:item.revised_prompt||'',usage:data.usage||null}}throw new Error('OpenAI hat keine Bilddatei geliefert.')}

export default async function handler(req,res){if(req.method!=='POST')return send(res,405,{error:'Nur POST ist erlaubt.'});let auth,jobId=null,model='';try{auth=await requireUser(req);const body=await readJson(req,18*1024*1024);const prompt=String(body.prompt||'').trim().slice(0,4000);if(!prompt)return send(res,400,{error:'Bild-Prompt fehlt.'});const aspect=Object.hasOwn(sizes,body.aspect)?body.aspect:'post';const size=sizes[aspect];const quality=['low','medium','high','auto'].includes(body.quality)?body.quality:env('OPENAI_IMAGE_QUALITY','medium');const background=['auto','opaque','transparent'].includes(body.background)?body.background:'auto';model=['gpt-image-2','gpt-image-1.5','gpt-image-1'].includes(body.model)?body.model:env('OPENAI_IMAGE_MODEL','gpt-image-2');const requestId=String(body.requestId||randomUUID());const estimated=estimate(model,quality,size);const kind=body.referenceImage?'image_edit':'image';const reservation=await reserveJob(req,{requestId,kind,model,prompt,units:1,format:size,quality,estimatedCostUsd:estimated,costConfirmed:body.costConfirmed,metadata:{aspect,background,hasReference:Boolean(body.referenceImage),hasMask:Boolean(body.maskImage),designId:body.designId||null}});jobId=reservation.job.id;if(reservation.duplicate&&reservation.job.status!=='reserved')return send(res,200,{duplicate:true,job:reservation.job});await moderate({text:prompt,imageDataUrl:body.referenceImage});await finishJob({jobId,status:'in_progress',progress:15});const key=env('OPENAI_API_KEY');if(!key)throw new Error('OPENAI_API_KEY fehlt in Vercel.');const format=background==='transparent'||body.maskImage?'png':'webp';const result=await generate({key,model,prompt,size,quality,background,reference:body.referenceImage,mask:body.maskImage,format});const stored=await uploadAsset({userId:auth.user.id,folder:'bilder',filename:`yildiz-ai-${requestId}.${format}`,buffer:result.buffer,mimeType:`image/${format}`,assetType:'image',sourceType:kind==='image_edit'?'editor':'ai',metadata:{model,quality,aspect,size,prompt,revisedPrompt:result.revisedPrompt,usage:result.usage,jobId}});await finishJob({jobId,status:'completed',progress:100,actualCostUsd:estimated,resultAssetId:stored.asset.id,metadataPatch:{assetId:stored.asset.id}});return send(res,200,{jobId,asset:stored.asset,signedUrl:stored.signedUrl,model,quality,aspect,estimatedCostUsd:estimated,edited:kind==='image_edit'});}catch(e){if(jobId)await finishJob({jobId,status:'failed',progress:100,actualCostUsd:0,errorMessage:e.message}).catch(()=>{});await logError({userId:auth?.user?.id,jobId,functionName:'ai/image',model,publicMessage:e.message||'Bildgenerierung fehlgeschlagen.',technicalMessage:e.technical||e.stack||e.message,retryable:true});return handleApiError(res,e,'Bildgenerierung fehlgeschlagen.')}}
