import { randomUUID } from 'node:crypto';
import sharp from 'sharp';
import { env, finishJob, handleApiError, logError, readJson, requireUser, reserveJob, send, serviceClient, uploadAsset } from '../_lib.js';
import { moderate } from '../_moderation.js';

function sizeFor(model, requested, aspect){const landscape=aspect==='landscape';const allowed=model==='sora-2-pro'?['720x1280','1280x720','1024x1792','1792x1024','1080x1920','1920x1080']:['720x1280','1280x720'];return allowed.includes(requested)?requested:(landscape?'1280x720':'720x1280')}
function cost(model,size,seconds){const s=Number(seconds);if(model!=='sora-2-pro')return s*.10;if(['1024x1792','1792x1024'].includes(size))return s*.50;if(['1080x1920','1920x1080'].includes(size))return s*.70;return s*.30}
function openErr(status,data){const raw=data?.error?.message||data?.message||'';if(status===401)return'Der OpenAI API-Key ist ungültig.';if(status===403)return'Sora ist für dieses OpenAI-Projekt nicht freigegeben.';if(status===429)return'OpenAI-Guthaben oder Sora-Limit erreicht.';return raw||`Sora HTTP ${status}`}
function dataImage(v){const m=String(v||'').match(/^data:(image\/(?:png|jpeg|webp));base64,(.+)$/);return m?{type:m[1],buffer:Buffer.from(m[2],'base64')}:null}
async function downloadAndStore(job,auth){const key=env('OPENAI_API_KEY');const r=await fetch(`https://api.openai.com/v1/videos/${encodeURIComponent(job.provider_job_id)}/content`,{headers:{Authorization:`Bearer ${key}`}});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(openErr(r.status,d))}const buffer=Buffer.from(await r.arrayBuffer());const stored=await uploadAsset({userId:auth.user.id,folder:'videos',filename:`yildiz-ai-${job.provider_job_id}.mp4`,buffer,mimeType:r.headers.get('content-type')||'video/mp4',assetType:'video',sourceType:'video',metadata:{jobId:job.id,providerJobId:job.provider_job_id,model:job.model,seconds:job.units,size:job.format}});await finishJob({jobId:job.id,status:'completed',progress:100,actualCostUsd:job.estimated_cost_usd,resultAssetId:stored.asset.id});return stored}

export default async function handler(req,res){
 let auth,jobId=null,model='';
 try{
  auth=await requireUser(req);
  const key=env('OPENAI_API_KEY');if(!key)throw new Error('OPENAI_API_KEY fehlt in Vercel.');
  if(req.method==='POST'){
   const body=await readJson(req,15*1024*1024);const prompt=String(body.prompt||'').trim().slice(0,4000);if(!prompt)return send(res,400,{error:'Video-Prompt fehlt.'});model=['sora-2','sora-2-pro'].includes(body.model)?body.model:env('OPENAI_VIDEO_MODEL','sora-2');const seconds=['4','8','12'].includes(String(body.seconds))?String(body.seconds):'4';const size=sizeFor(model,String(body.size||''),body.aspect);const requestId=String(body.requestId||randomUUID());const estimated=cost(model,size,seconds);const reservation=await reserveJob(req,{requestId,kind:'video',model,prompt,units:Number(seconds),format:size,quality:'',estimatedCostUsd:estimated,costConfirmed:body.costConfirmed,metadata:{aspect:body.aspect||'portrait',reference:Boolean(body.referenceImage)}});jobId=reservation.job.id;if(reservation.duplicate&&reservation.job.provider_job_id)return send(res,200,{duplicate:true,job:reservation.job});await moderate({text:prompt,imageDataUrl:body.referenceImage});await finishJob({jobId,status:'in_progress',progress:5});const form=new FormData();form.append('model',model);form.append('prompt',`${prompt}\nPremium commercial quality, coherent motion, stable identity, realistic physics, controlled camera, no random text, no watermark.`);form.append('size',size);form.append('seconds',seconds);const reference=dataImage(body.referenceImage);if(reference){const [w,h]=size.split('x').map(Number);const prepared=await sharp(reference.buffer).resize(w,h,{fit:'cover',position:'centre'}).png().toBuffer();form.append('input_reference',new Blob([prepared],{type:'image/png'}),'reference.png');}const response=await fetch('https://api.openai.com/v1/videos',{method:'POST',headers:{Authorization:`Bearer ${key}`},body:form});const data=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(openErr(response.status,data)),{status:response.status,technical:data?.error?.message});if(!data.id)throw new Error('OpenAI hat keine Video-ID geliefert.');const status=data.status==='completed'?'in_progress':data.status==='queued'?'queued':'in_progress';const job=await finishJob({jobId,status,progress:Number(data.progress||1),providerJobId:data.id,metadataPatch:{openai:data}});if(data.status==='completed'){const stored=await downloadAndStore(job,auth);return send(res,200,{job:{...job,status:'completed',result_asset_id:stored.asset.id},asset:stored.asset,signedUrl:stored.signedUrl,estimatedCostUsd:estimated})}return send(res,200,{job,provider:data,estimatedCostUsd:estimated,message:'Der Auftrag läuft serverseitig weiter. Du kannst die Seite schließen.'});
  }
  if(req.method==='GET'){
   const id=String(req.query?.jobId||'');if(!id)return send(res,400,{error:'jobId fehlt.'});const db=serviceClient();const {data:job,error}=await db.from('ai_jobs').select('*').eq('id',id).eq('user_id',auth.user.id).single();if(error||!job)throw Object.assign(new Error('Videoauftrag nicht gefunden.'),{status:404});jobId=job.id;model=job.model;if(job.status==='completed'&&job.result_asset_id){const {data:asset}=await db.from('media_assets').select('*').eq('id',job.result_asset_id).single();const {data:signed}=await db.storage.from(asset.bucket).createSignedUrl(asset.storage_path,3600);return send(res,200,{job,asset,signedUrl:signed?.signedUrl})}if(!job.provider_job_id)return send(res,200,{job});const response=await fetch(`https://api.openai.com/v1/videos/${encodeURIComponent(job.provider_job_id)}`,{headers:{Authorization:`Bearer ${key}`}});const data=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(openErr(response.status,data)),{status:response.status});if(data.status==='failed'){const updated=await finishJob({jobId:job.id,status:'failed',progress:100,actualCostUsd:0,errorMessage:data?.error?.message||'Sora fehlgeschlagen.'});return send(res,200,{job:updated,provider:data})}if(data.status==='completed'){const updated=await finishJob({jobId:job.id,status:'in_progress',progress:100,providerJobId:data.id});const stored=await downloadAndStore(updated,auth);const {data:done}=await db.from('ai_jobs').select('*').eq('id',job.id).single();return send(res,200,{job:done,asset:stored.asset,signedUrl:stored.signedUrl,provider:data})}const updated=await finishJob({jobId:job.id,status:data.status==='queued'?'queued':'in_progress',progress:Number(data.progress||0),providerJobId:data.id});return send(res,200,{job:updated,provider:data});
  }
  if(req.method==='DELETE'){
   const id=String(req.query?.jobId||'');const db=serviceClient();const {data:job}=await db.from('ai_jobs').select('*').eq('id',id).eq('user_id',auth.user.id).single();if(!job)throw Object.assign(new Error('Videoauftrag nicht gefunden.'),{status:404});if(job.provider_job_id)await fetch(`https://api.openai.com/v1/videos/${encodeURIComponent(job.provider_job_id)}`,{method:'DELETE',headers:{Authorization:`Bearer ${key}`}}).catch(()=>{});const updated=await finishJob({jobId:job.id,status:'canceled',progress:100,actualCostUsd:0});return send(res,200,{job:updated});
  }
  return send(res,405,{error:'Nicht unterstützte Methode.'});
 }catch(e){if(jobId&&req.method==='POST')await finishJob({jobId,status:'failed',progress:100,actualCostUsd:0,errorMessage:e.message}).catch(()=>{});await logError({userId:auth?.user?.id,jobId,functionName:'ai/video',model,publicMessage:e.message||'Video fehlgeschlagen.',technicalMessage:e.technical||e.stack||e.message,retryable:true});return handleApiError(res,e,'Video fehlgeschlagen.')}
}
