import Stripe from 'stripe';
import { env, logError, readRaw, send, serviceClient } from '../_lib.js';
export const config={api:{bodyParser:false}};
function status(s){return ['active','trialing','past_due','paused','canceled','incomplete'].includes(s)?s:'incomplete'}
async function processEvent(event){const db=serviceClient();const o=event.data.object;if(event.type==='checkout.session.completed'){const userId=o.metadata?.user_id||o.client_reference_id;const productId=o.metadata?.product_id;if(!userId||!productId)return;if(o.mode==='subscription'){await db.from('subscriptions').upsert({user_id:userId,product_id:productId,provider:'stripe',provider_customer_id:String(o.customer||''),provider_subscription_id:String(o.subscription||''),status:'active',updated_at:new Date().toISOString()},{onConflict:'user_id'})}else{const {data:p}=await db.from('products').select('*').eq('id',productId).single();await db.from('purchases').upsert({user_id:userId,product_id:productId,provider:'stripe',provider_payment_id:String(o.payment_intent||o.id),amount_cents:Number(o.amount_total||p?.price_cents||0),currency:String(o.currency||p?.currency||'eur'),status:o.payment_status==='paid'?'paid':'pending',updated_at:new Date().toISOString()},{onConflict:'provider,provider_payment_id'})}}
if(event.type.startsWith('customer.subscription.')){const userId=o.metadata?.user_id;const productId=o.metadata?.product_id;const updates={provider:'stripe',provider_customer_id:String(o.customer||''),provider_subscription_id:String(o.id||''),status:event.type==='customer.subscription.deleted'?'canceled':status(o.status),current_period_end:o.current_period_end?new Date(o.current_period_end*1000).toISOString():null,cancel_at_period_end:Boolean(o.cancel_at_period_end),updated_at:new Date().toISOString()};if(userId){updates.user_id=userId;if(productId)updates.product_id=productId;await db.from('subscriptions').upsert(updates,{onConflict:'user_id'})}else await db.from('subscriptions').update(updates).eq('provider_subscription_id',o.id)}
if(event.type==='invoice.payment_failed'&&o.subscription)await db.from('subscriptions').update({status:'past_due',updated_at:new Date().toISOString()}).eq('provider_subscription_id',String(o.subscription));
if(event.type==='charge.refunded'){const id=String(o.payment_intent||o.id);await db.from('purchases').update({status:'refunded',updated_at:new Date().toISOString()}).eq('provider_payment_id',id)} }
export default async function handler(req,res){if(req.method!=='POST')return send(res,405,{error:'Nur POST ist erlaubt.'});try{const raw=await readRaw(req,5*1024*1024);const signature=req.headers['stripe-signature'];const stripe=new Stripe(env('STRIPE_SECRET_KEY'));const event=stripe.webhooks.constructEvent(raw,signature,env('STRIPE_WEBHOOK_SECRET'));const db=serviceClient();const {data:existing}=await db.from('payment_events').select('id').eq('provider','stripe').eq('provider_event_id',event.id).maybeSingle();if(existing)return send(res,200,{ok:true,duplicate:true});await db.from('payment_events').insert({provider:'stripe',provider_event_id:event.id,event_type:event.type,payload:event,processed:false});await processEvent(event);await db.from('payment_events').update({processed:true}).eq('provider','stripe').eq('provider_event_id',event.id);return send(res,200,{received:true});}catch(e){await logError({functionName:'webhooks/stripe',publicMessage:'Stripe-Webhook fehlgeschlagen.',technicalMessage:e.stack||e.message,retryable:true});return send(res,400,{error:'Ungültiger Stripe-Webhook.'})}}
