import { handleApiError, rateLimit, requireUser, send } from '../_lib.js';

const UA='Mozilla/5.0 AppleWebKit/537.36 Chrome/124 Safari/537.36 YildizAI/10';
function safeUrl(v){try{const u=new URL(String(v||''));return ['http:','https:'].includes(u.protocol)?u.toString():''}catch{return ''}}
async function text(url,headers={}){const c=new AbortController();const t=setTimeout(()=>c.abort(),14000);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':UA,'Accept-Language':'de-DE,de;q=0.9',...headers}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.text()}finally{clearTimeout(t)}}
async function ddg(q){const home=await text(`https://duckduckgo.com/?q=${encodeURIComponent(q)}&iax=images&ia=images`);const token=home.match(/vqd=["']?([\d-]+)["']?/i)?.[1]||home.match(/"vqd"\s*:\s*"([^"]+)"/i)?.[1];if(!token)throw new Error('Suchtoken fehlt.');const raw=await text(`https://duckduckgo.com/i.js?l=de-de&o=json&q=${encodeURIComponent(q)}&vqd=${encodeURIComponent(token)}&f=,,,`,{Referer:'https://duckduckgo.com/'});const d=JSON.parse(raw);return (d.results||[]).slice(0,12).map((x,i)=>({id:`ddg-${i}`,title:String(x.title||q).replace(/<[^>]+>/g,''),imageUrl:safeUrl(x.image),thumbnailUrl:safeUrl(x.thumbnail),sourceUrl:safeUrl(x.url),provider:String(x.source||'DuckDuckGo'),usageRightsNote:'Nutzungsrechte wurden nicht automatisch geprüft. Vor kommerzieller Nutzung die Lizenz auf der Quellseite kontrollieren.',width:Number(x.width||0),height:Number(x.height||0)})).filter(x=>x.imageUrl||x.thumbnailUrl)}
async function commons(q){const u=new URL('https://commons.wikimedia.org/w/api.php');for(const [k,v] of Object.entries({action:'query',generator:'search',gsrsearch:q,gsrnamespace:'6',gsrlimit:'12',prop:'imageinfo|info',iiprop:'url|mime|size|extmetadata',iiurlwidth:'800',inprop:'url',format:'json',origin:'*'}))u.searchParams.set(k,v);const d=JSON.parse(await text(u));return Object.values(d?.query?.pages||{}).map((p,i)=>{const x=p.imageinfo?.[0]||{};const license=x.extmetadata?.LicenseShortName?.value||'Lizenz auf Wikimedia Commons prüfen';return{id:`commons-${p.pageid||i}`,title:String(p.title||q).replace(/^File:/i,''),imageUrl:safeUrl(x.url),thumbnailUrl:safeUrl(x.thumburl||x.url),sourceUrl:safeUrl(p.canonicalurl||p.fullurl),provider:'Wikimedia Commons',usageRightsNote:license,width:Number(x.width||0),height:Number(x.height||0)}}).filter(x=>x.imageUrl)}

export default async function handler(req,res){
 if(!['GET','POST'].includes(req.method))return send(res,405,{error:'Nur GET oder POST ist erlaubt.'});
 try{const {user}=await requireUser(req);await rateLimit({userId:user.id,endpoint:'image-search',limit:40,windowSeconds:600});const q=String(req.method==='GET'?req.query?.q:req.body?.query||'').replace(/\s+/g,' ').trim().slice(0,180);if(!q)return send(res,400,{error:'Suchbegriff fehlt.'});let results=[];const warnings=[];try{results=await ddg(q)}catch(e){warnings.push(`DuckDuckGo: ${e.message}`)}if(results.length<5){try{const c=await commons(q);const known=new Set(results.map(x=>x.imageUrl));results.push(...c.filter(x=>!known.has(x.imageUrl)))}catch(e){warnings.push(`Wikimedia: ${e.message}`)}}return send(res,200,{query:q,mode:'existing-product-image-search',free:true,results:results.slice(0,12),warning:results.length?undefined:'Keine direkten Bilder gefunden.',technical:warnings});}catch(e){return handleApiError(res,e,'Bildsuche fehlgeschlagen.')}}
