import {useEffect,useState} from 'react';
import {FileClock,FileImage,Film,Globe2,LayoutTemplate,RefreshCw,RotateCcw,Trash2,X} from 'lucide-react';
import {api} from '../api.js';
const icons={flyer:LayoutTemplate,image:FileImage,video:Film,website:Globe2};
const labels={flyer:'Flyer',image:'Bilddesign',video:'Video',website:'Website'};
export default function Projects({onOpen,refreshKey,uiText={}}){
 const[projects,setProjects]=useState([]),[status,setStatus]=useState(''),[versionProject,setVersionProject]=useState(null),[versions,setVersions]=useState([]);
 async function load(){setStatus('Laden …');try{const r=await api('/api/projects');setProjects(r.projects||[]);setStatus('')}catch(e){setStatus(e.message)}}
 useEffect(()=>{load()},[refreshKey]);
 async function remove(p){if(!confirm(`„${p.name}“ löschen?`))return;try{await api(`/api/projects/${p.id}`,{method:'DELETE'});load()}catch(e){setStatus(e.message)}}
 async function showVersions(p){setVersionProject(p);setVersions([]);setStatus('Versionen laden …');try{const r=await api(`/api/projects/${p.id}/versions`);setVersions(r.versions||[]);setStatus('')}catch(e){setStatus(e.message)}}
 async function restore(v){if(!confirm(`Version ${v.versionNo} wiederherstellen? Der jetzige Stand bleibt als neue Version erhalten.`))return;try{const r=await api(`/api/project-versions/${v.id}/restore`,{method:'POST',body:'{}'});setVersionProject(null);setVersions([]);setStatus('Version wiederhergestellt.');await load();onOpen?.(r.project)}catch(e){setStatus(e.message)}}
 return <section className="projects-page"><div className="page-heading"><div><h2>{uiText.projectsTitle||'Projekte'}</h2><p>{uiText.projectsSubtitle||'Deine gespeicherten Designs, Videos und Webseiten.'}</p></div><button onClick={load}><RefreshCw size={17}/>Aktualisieren</button></div>{status&&<div className="status-line">{status}</div>}<div className="project-grid">{projects.map(p=>{const Icon=icons[p.type]||LayoutTemplate;return <article className="project-card" key={p.id} onClick={()=>onOpen(p)}><div className="project-icon"><Icon size={28}/></div><div><span>{labels[p.type]||p.type}</span><h3>{p.name}</h3><p>{new Date(p.updatedAt).toLocaleString('de-DE')}</p></div><div className="project-card-actions"><button title="Versionen" onClick={e=>{e.stopPropagation();showVersions(p)}}><FileClock size={17}/></button><button className="danger-icon" onClick={e=>{e.stopPropagation();remove(p)}}><Trash2 size={17}/></button></div></article>})}{!projects.length&&!status&&<div className="empty-state">Noch keine Projekte gespeichert.</div>}</div>{versionProject&&<div className="version-overlay" onClick={()=>setVersionProject(null)}><div className="version-dialog" onClick={e=>e.stopPropagation()}><div className="panel-title"><FileClock size={20}/><div><h3>Versionsverlauf</h3><p>{versionProject.name} · maximal 30 Versionen</p></div><button onClick={()=>setVersionProject(null)}><X size={18}/></button></div><div className="security-list">{versions.map(v=><div className="security-row" key={v.id}><div><b>Version {v.versionNo}</b><span>{new Date(v.createdAt).toLocaleString('de-DE')} · {v.reason}</span></div><button onClick={()=>restore(v)}><RotateCcw size={15}/>Wiederherstellen</button></div>)}{!versions.length&&!status&&<div className="empty-state">Keine Versionen gefunden.</div>}</div></div></div>}</section>
}
