import {useEffect,useMemo,useState} from 'react';
import {Bell,CheckCircle2,Database,Download,ExternalLink,FileClock,Globe2,KeyRound,RefreshCw,Search,Server,ShieldCheck,Trash2,TriangleAlert} from 'lucide-react';
import {api,setToken} from '../api.js';
const initialBrand={companyName:'',logoUrl:'',primaryColor:'#63c7ff',secondaryColor:'#ffd400',fontFamily:'Arial'};
const date=v=>{try{return new Date(v).toLocaleString('de-DE')}catch{return''}};
function downloadJson(name,value){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'});if(!blob.size)throw new Error('Exportdatei ist leer.');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function StatusCard({title,item,icon:Icon}){const good=['online','configured'].includes(item?.state);return <article className={`security-status ${good?'good':'warn'}`}><Icon size={20}/><div><b>{title}</b><span>{item?.label||'Unbekannt'}</span></div></article>}
export default function SafetyCenter({user,onLogout}){
  const[data,setData]=useState(null),[status,setStatus]=useState('Laden …'),[searchText,setSearchText]=useState(''),[searchResult,setSearchResult]=useState(null),[searching,setSearching]=useState(false),[brand,setBrand]=useState(initialBrand),[deletePassword,setDeletePassword]=useState(''),[deleteConfirmation,setDeleteConfirmation]=useState('');
  const unread=useMemo(()=>data?.notifications?.filter(n=>!n.readAt).length||0,[data]);
  async function load(){setStatus('Aktualisieren …');try{const r=await api('/api/platform?action=overview');setData(r);setBrand({...initialBrand,...(r.brand||{})});setStatus('');const done=(r.notifications||[]).find(n=>!n.readAt&&n.kind==='success');if(done&&'Notification'in window&&Notification.permission==='granted')new Notification(done.title,{body:done.message||'Yildiz AI ist fertig.'})}catch(e){setStatus(e.message)}}
  useEffect(()=>{load();const timer=setInterval(load,30000);return()=>clearInterval(timer)},[]);
  async function enableNotifications(){if(!('Notification'in window))return setStatus('Browser-Benachrichtigungen werden nicht unterstützt.');const p=await Notification.requestPermission();setStatus(p==='granted'?'Benachrichtigungen aktiviert.':'Benachrichtigungen nicht erlaubt.')}
  async function mark(id){try{await api('/api/platform?action=mark-notification',{method:'POST',body:JSON.stringify({id})});load()}catch(e){setStatus(e.message)}}
  async function webSearch(){if(!searchText.trim())return;setSearching(true);setSearchResult(null);setStatus('Websuche läuft …');try{setSearchResult(await api('/api/platform?action=search',{method:'POST',body:JSON.stringify({query:searchText})}));setStatus('')}catch(e){setStatus(e.message)}finally{setSearching(false)}}
  async function exportAll(){try{downloadJson(`yildiz-ai-daten-${new Date().toISOString().slice(0,10)}.json`,await api('/api/platform?action=export'));setStatus('Vollständiger Datenexport erstellt.')}catch(e){setStatus(e.message)}}
  async function endSessions(){if(!confirm('Alle anderen Geräte abmelden?'))return;try{const r=await api('/api/platform?action=end-sessions',{method:'POST',body:'{}'});setStatus(`${r.ended||0} andere Sitzung(en) beendet.`);load()}catch(e){setStatus(e.message)}}
  async function saveBrand(){try{await api('/api/platform?action=save-brand',{method:'POST',body:JSON.stringify(brand)});setStatus('Markenprofil gespeichert.');load()}catch(e){setStatus(e.message)}}
  async function resolveError(id){try{await api('/api/platform?action=resolve-error',{method:'POST',body:JSON.stringify({id})});load()}catch(e){setStatus(e.message)}}
  async function deleteAccount(){if(!confirm('Konto und alle Daten wirklich unwiderruflich löschen?'))return;try{await api('/api/platform?action=delete-account',{method:'POST',body:JSON.stringify({password:deletePassword,confirmation:deleteConfirmation})});setToken('');localStorage.removeItem('yildiz_ai_guest');onLogout?.();location.reload()}catch(e){setStatus(e.message)}}
  return <section className="security-page">
    <div className="page-heading"><div><h2><ShieldCheck size={23}/> Sicherheit & Daten</h2><p>Projekte, Aufträge, Sitzungen, Quellen und persönliche Daten kontrollieren.</p></div><button onClick={load}><RefreshCw size={17}/>Aktualisieren</button></div>
    {status&&<div className="status-line">{status}</div>}
    <div className="security-status-grid"><StatusCard title="Supabase Datenbank" item={data?.system?.supabaseDatabase} icon={Database}/><StatusCard title="Supabase Storage" item={data?.system?.supabaseStorage} icon={Server}/><StatusCard title="Gemini" item={data?.system?.gemini} icon={Globe2}/><StatusCard title="OpenAI Bilder" item={data?.system?.openaiImages} icon={CheckCircle2}/><StatusCard title="Sora Videos" item={data?.system?.soraVideos} icon={CheckCircle2}/></div>
    <div className="security-grid">
      <article className="security-panel"><div className="panel-title"><FileClock size={19}/><div><h3>KI-Aufträge</h3><p>Bleiben nach Neuladen sichtbar.</p></div></div><div className="security-list">{(data?.jobs||[]).map(j=><div className="security-row" key={j.id}><div><b>{j.kind==='video'?'Video':'Bild'} · {j.model||'Modell'}</b><span>{date(j.createdAt)}</span></div><span className={`job-state ${j.status}`}>{j.status}</span>{j.error&&<small>{j.error}</small>}</div>)}{!data?.jobs?.length&&<div className="empty-state">Noch keine KI-Aufträge.</div>}</div></article>
      <article className="security-panel"><div className="panel-title"><Bell size={19}/><div><h3>Benachrichtigungen {unread?`(${unread})`:''}</h3><p>Fertige und fehlgeschlagene Aufträge.</p></div></div><button className="secondary-button" onClick={enableNotifications}>Browser-Benachrichtigungen aktivieren</button><div className="security-list">{(data?.notifications||[]).map(n=><button className={`notification-row ${n.readAt?'read':''}`} key={n.id} onClick={()=>mark(n.id)}><div><b>{n.title}</b><span>{n.message}</span></div><small>{date(n.createdAt)}</small></button>)}{!data?.notifications?.length&&<div className="empty-state">Keine Benachrichtigungen.</div>}</div></article>
    </div>
    <article className="security-panel"><div className="panel-title"><Search size={19}/><div><h3>Aktuelle Websuche mit Quellen</h3><p>Erst suchen, dann mit Quellen antworten.</p></div></div><div className="security-search"><input value={searchText} onChange={e=>setSearchText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')webSearch()}} placeholder="Was möchtest du aktuell prüfen?"/><button onClick={webSearch} disabled={searching}>{searching?'Suche …':'Suchen'}</button></div>{searchResult&&<div className="search-answer"><p>{searchResult.answer}</p><div className="source-links">{(searchResult.sources||[]).map((s,i)=><a key={i} href={s.url} target="_blank" rel="noreferrer"><ExternalLink size={14}/>{s.title}</a>)}</div></div>}</article>
    <div className="security-grid">
      <article className="security-panel"><div className="panel-title"><ShieldCheck size={19}/><div><h3>Markenprofil</h3><p>Logo, Farben und Schrift zentral speichern.</p></div></div><div className="security-form"><label>Firmenname<input value={brand.companyName} onChange={e=>setBrand({...brand,companyName:e.target.value})}/></label><label>Logo-URL<input value={brand.logoUrl} onChange={e=>setBrand({...brand,logoUrl:e.target.value})}/></label><label>Primärfarbe<input type="color" value={brand.primaryColor} onChange={e=>setBrand({...brand,primaryColor:e.target.value})}/></label><label>Sekundärfarbe<input type="color" value={brand.secondaryColor} onChange={e=>setBrand({...brand,secondaryColor:e.target.value})}/></label><label>Schrift<input value={brand.fontFamily} onChange={e=>setBrand({...brand,fontFamily:e.target.value})}/></label><button onClick={saveBrand}>Markenprofil speichern</button></div></article>
      <article className="security-panel"><div className="panel-title"><KeyRound size={19}/><div><h3>Sitzungen & Datenschutz</h3><p>{data?.sessionCount||0} aktive Sitzung(en).</p></div></div><div className="security-actions"><button onClick={endSessions}>Andere Geräte abmelden</button><button onClick={exportAll}><Download size={16}/>Alle Daten exportieren</button></div><hr/><div className="danger-zone"><h4><TriangleAlert size={17}/>Konto vollständig löschen</h4><input type="password" value={deletePassword} onChange={e=>setDeletePassword(e.target.value)} placeholder="Aktuelles Passwort"/><input value={deleteConfirmation} onChange={e=>setDeleteConfirmation(e.target.value)} placeholder={`Benutzername exakt eingeben: ${user?.username||''}`}/><button onClick={deleteAccount}><Trash2 size={16}/>Konto und alle Daten löschen</button></div></article>
    </div>
    {user?.role==='admin'&&<article className="security-panel"><div className="panel-title"><TriangleAlert size={19}/><div><h3>Admin-Fehlerprotokoll</h3><p>Fehlgeschlagene KI-Aufträge ohne Geheimschlüssel.</p></div></div><div className="security-list">{(data?.adminErrors||[]).map(e=><div className={`security-row ${e.resolvedAt?'resolved':''}`} key={e.id}><div><b>{e.function||'Funktion'} · {e.model||'Modell'}</b><span>{date(e.createdAt)}</span></div><small>{e.message}</small>{!e.resolvedAt&&<button onClick={()=>resolveError(e.id)}>Als erledigt markieren</button>}</div>)}{!data?.adminErrors?.length&&<div className="empty-state">Keine protokollierten Fehler.</div>}</div></article>}
  </section>
}
