import { randomUUID } from 'node:crypto';
import Stripe from 'stripe';
import { env, handleApiError, readJson, requireUser, send, serviceClient } from '../_lib.js';
import { paypalFetch } from '../_paypal.js';

function appUrl(){return env('APP_URL')||env('VITE_APP_URL')||'http://localhost:5173'}
function stripeClient(){const key=env('STRIPE_SECRET_KEY');if(!key)throw new Error('STRIPE_SECRET_KEY fehlt.');return new Stripe(key)}

export default async function handler(req,res){if(req.method!=='POST')return send(res,405,{error:'Nur POST ist erlaubt.'});try{const {user}=await requireUser(req);const body=await readJson(req);const productId=String(body.productId||'');const requestId=String(body.requestId||randomUUID());const db=serviceClient();const [{data:settings},{data:product}]=await Promise.all([db.from('app_settings').select('*').eq('id',1).single(),db.from('products').select('*').eq('id',productId).single()]);if(!settings?.payments_enabled)throw Object.assign(new Error('Zahlungen sind derzeit ausgeschaltet. Der Preis bleibt sichtbar, aber ein Kauf ist nicht möglich.'),{status:403});if(!product?.visible||!product?.active||!product?.purchasable)throw Object.assign(new Error('Dieses Produkt ist derzeit nicht kaufbar.'),{status:403});if(product.price_cents<=0)throw new Error('Produktpreis ist ungültig.');const provider=settings.active_payment_provider;const base=appUrl();if(provider==='stripe'){const stripe=stripeClient();const priceData={currency:product.currency||'eur',unit_amount:product.price_cents,product_data:{name:product.name,description:product.description||undefined,metadata:{yildiz_product_id:product.id}}};if(product.kind==='subscription')priceData.recurring={interval:product.billing_interval||'month'};const params={mode:product.kind==='subscription'?'subscription':'payment',payment_method_types:['card'],line_items:[{price_data:priceData,quantity:1}],success_url:`${base}/?payment=success&session_id={CHECKOUT_SESSION_ID}`,cancel_url:`${base}/?payment=cancel`,client_reference_id:user.id,customer_email:user.email||undefined,metadata:{user_id:user.id,product_id:product.id,request_id:requestId},allow_promotion_codes:true};if(product.kind==='subscription')params.subscription_data={metadata:{user_id:user.id,product_id:product.id}};else params.payment_intent_data={metadata:{user_id:user.id,product_id:product.id}};const options={idempotencyKey:`${user.id}-${product.id}-${requestId}`};const connected=env('STRIPE_CONNECTED_ACCOUNT_ID');if(connected)options.stripeAccount=connected;const session=await stripe.checkout.sessions.create(params,options);return send(res,200,{provider:'stripe',checkoutUrl:session.url,sessionId:session.id,message:'Kreditkartendaten werden ausschließlich bei Stripe eingegeben und nicht von Yildiz AI gespeichert.'})}
if(provider==='paypal'){if(product.kind==='subscription'){if(!product.paypal_plan_id)throw new Error('Für dieses Abo fehlt die PayPal Plan-ID.');const sub=await paypalFetch('/v1/billing/subscriptions',{method:'POST',headers:{'PayPal-Request-Id':requestId},body:JSON.stringify({plan_id:product.paypal_plan_id,custom_id:`${user.id}|${product.id}`,subscriber:user.email?{email_address:user.email}:undefined,application_context:{brand_name:'Yildiz AI',locale:'de-DE',user_action:'SUBSCRIBE_NOW',return_url:`${base}/?paypal=subscription-success`,cancel_url:`${base}/?payment=cancel`}})});const link=sub.links?.find(x=>x.rel==='approve')?.href;if(!link)throw new Error('PayPal hat keinen Bestätigungslink geliefert.');return send(res,200,{provider:'paypal',checkoutUrl:link,subscriptionId:sub.id})}const order=await paypalFetch('/v2/checkout/orders',{method:'POST',headers:{'PayPal-Request-Id':requestId},body:JSON.stringify({intent:'CAPTURE',purchase_units:[{custom_id:`${user.id}|${product.id}`,description:product.name,amount:{currency_code:String(product.currency||'eur').toUpperCase(),value:(product.price_cents/100).toFixed(2)}}],application_context:{brand_name:'Yildiz AI',user_action:'PAY_NOW',return_url:`${base}/?paypal=capture`,cancel_url:`${base}/?payment=cancel`}})});const link=order.links?.find(x=>x.rel==='approve')?.href;if(!link)throw new Error('PayPal hat keinen Bestätigungslink geliefert.');return send(res,200,{provider:'paypal',checkoutUrl:link,orderId:order.id})}
throw new Error('Unbekannter Zahlungsanbieter.');}catch(e){return handleApiError(res,e,'Bezahlvorgang konnte nicht gestartet werden.')}}
