import { randomUUID } from 'node:crypto';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { Document, Packer, Paragraph, HeadingLevel, Table, TableRow, TableCell, TextRun } from 'docx';
import ExcelJS from 'exceljs';
import { finishJob, handleApiError, logError, readJson, requireUser, reserveJob, send, uploadAsset } from '../_lib.js';

function cleanName(value, extension){const base=String(value||'Yildiz-AI-Datei').replace(/\.[^.]+$/,'').replace(/[^a-zA-Z0-9äöüÄÖÜß._ -]/g,'').trim().slice(0,80)||'Yildiz-AI-Datei';return `${base}.${extension}`}
function lines(text,max=88){const out=[];for(const paragraph of String(text||'').split(/\n/)){let line='';for(const word of paragraph.split(/\s+/)){if(!word)continue;if(`${line} ${word}`.trim().length>max){out.push(line);line=word}else line=`${line} ${word}`.trim()}out.push(line)}return out}
async function pdfBuffer(body){const pdf=await PDFDocument.create();const font=await pdf.embedFont(StandardFonts.Helvetica);const bold=await pdf.embedFont(StandardFonts.HelveticaBold);let page=pdf.addPage([595.28,841.89]);let y=790;const add=(t,size=11,b=false)=>{for(const line of lines(t,size>16?55:88)){if(y<55){page=pdf.addPage([595.28,841.89]);y=790}page.drawText(line,{x:50,y,size,font:b?bold:font,color:rgb(.08,.08,.1)});y-=size+6}};add(body.title||'Yildiz AI Dokument',20,true);y-=8;add(body.content||'',11,false);return Buffer.from(await pdf.save())}
function docxParagraphs(body){const arr=[new Paragraph({text:body.title||'Yildiz AI Dokument',heading:HeadingLevel.TITLE})];for(const p of String(body.content||'').split(/\n+/))arr.push(new Paragraph({children:[new TextRun(p)]}));if(Array.isArray(body.table)&&body.table.length){arr.push(new Table({rows:body.table.map((row,i)=>new TableRow({children:(Array.isArray(row)?row:[row]).map(v=>new TableCell({children:[new Paragraph({children:[new TextRun({text:String(v??''),bold:i===0})]})]}))}))}))}return arr}
async function docxBuffer(body){const doc=new Document({sections:[{properties:{},children:docxParagraphs(body)}]});return Buffer.from(await Packer.toBuffer(doc))}
async function xlsxBuffer(body){const book=new ExcelJS.Workbook();const sheet=book.addWorksheet(String(body.sheetName||'Tabelle').slice(0,31));const rows=Array.isArray(body.rows)&&body.rows.length?body.rows:[[body.title||'Yildiz AI Tabelle'],...String(body.content||'').split(/\n/).map(x=>[x])];for(const row of rows)sheet.addRow(Array.isArray(row)?row:[row]);if(rows.length)sheet.getRow(1).font={bold:true};sheet.columns.forEach(c=>{c.width=Math.min(50,Math.max(12,...c.values.filter(Boolean).map(v=>String(v).length+2))) });return Buffer.from(await book.xlsx.writeBuffer())}

export default async function handler(req,res){if(req.method!=='POST')return send(res,405,{error:'Nur POST ist erlaubt.'});let auth,jobId=null;try{auth=await requireUser(req);const body=await readJson(req,3*1024*1024);const type=String(body.type||'pdf').toLowerCase();if(!['pdf','docx','xlsx'].includes(type))return send(res,400,{error:'Erlaubt sind PDF, DOCX und XLSX.'});const requestId=String(body.requestId||randomUUID());const reservation=await reserveJob(req,{requestId,kind:'document',model:'server-document-generator',prompt:String(body.title||body.content||'Datei erstellen').slice(0,4000),units:1,format:type,quality:'',estimatedCostUsd:0,costConfirmed:true,metadata:{filename:body.filename||'',type}});jobId=reservation.job.id;if(reservation.duplicate&&reservation.job.result_asset_id)return send(res,200,{duplicate:true,job:reservation.job});await finishJob({jobId,status:'in_progress',progress:20});let buffer,mime,folder='pdf',assetType=type;if(type==='pdf'){buffer=await pdfBuffer(body);mime='application/pdf'}else if(type==='docx'){buffer=await docxBuffer(body);mime='application/vnd.openxmlformats-officedocument.wordprocessingml.document';folder='uploads'}else{buffer=await xlsxBuffer(body);mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';folder='uploads'}if(!buffer?.length)throw new Error('Die erzeugte Datei ist leer.');const filename=cleanName(body.filename,type);const stored=await uploadAsset({userId:auth.user.id,folder,filename,buffer,mimeType:mime,assetType,sourceType:'document',originalName:filename,metadata:{jobId,title:body.title||'',verified:{exists:true,sizeGreaterThanZero:true,mimeType:mime}}});await finishJob({jobId,status:'completed',progress:100,actualCostUsd:0,resultAssetId:stored.asset.id});return send(res,200,{jobId,asset:stored.asset,signedUrl:stored.signedUrl,verified:true});}catch(e){if(jobId)await finishJob({jobId,status:'failed',progress:100,actualCostUsd:0,errorMessage:e.message}).catch(()=>{});await logError({userId:auth?.user?.id,jobId,functionName:'files/create',publicMessage:e.message||'Datei konnte nicht erstellt werden.',technicalMessage:e.stack||e.message,retryable:true});return handleApiError(res,e,'Datei konnte nicht erstellt werden.')}}
